---
all:
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    #ansible_password: "xx"
  children:
    haproxy_hosts:
      hosts:
        HAPROXY_IP: {}
    apache_hosts:
      hosts:
        # apache_ip[x]: {}            
